# Generated by Django 3.0.5 on 2020-04-17 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('category_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=200)),
                ('added_date', models.DateTimeField(blank=True, default='2020-04-17 12:08:06')),
                ('Updated_date', models.DateTimeField(blank=True, default='2020-04-17 12:08:06')),
                ('Status', models.SmallIntegerField(default=1)),
            ],
        ),
    ]
